import { Seed, Location } from '@/types/farming';

// Mock data for demonstration with Kenya locations
const mockSeeds: Seed[] = [
  // High rainfall seeds suitable for Kenya
  {
    _id: '1',
    name: 'Rice (Paddy)',
    rainfallRequirement: 'high',
    description: 'Staple crop that thrives in waterlogged conditions and high rainfall areas, particularly suitable for Mwea irrigation schemes.',
    growingSeason: '3-4 months (Long rains)',
    waterRequirement: 'High - 1200-1500mm annually',
    yield: '2.5-4.5 tons per hectare',
    suitableRegions: ['Central', 'Western', 'Nyanza', 'Coast'],
    climateZone: 'Tropical Wet',
    soilType: ['Clay', 'Loamy', 'Alluvial'],
    plantingTime: 'March-April',
    harvestTime: 'July-August',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: '2',
    name: 'Sugarcane',
    rainfallRequirement: 'high',
    description: 'Cash crop that requires substantial water throughout its growing period, major crop in western Kenya.',
    growingSeason: '12-18 months',
    waterRequirement: 'Very High - 1500-2500mm annually',
    yield: '60-80 tons per hectare',
    suitableRegions: ['Western', 'Nyanza', 'Coast', 'Rift Valley'],
    climateZone: 'Tropical Semi-Arid',
    soilType: ['Loamy', 'Black Cotton', 'Alluvial'],
    plantingTime: 'March-May',
    harvestTime: '12-18 months after planting',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: '3',
    name: 'Banana',
    rainfallRequirement: 'high',
    description: 'Important fruit crop that needs consistent moisture for optimal growth, staple in many highland areas.',
    growingSeason: '9-12 months',
    waterRequirement: 'High - 1200-1500mm annually with good distribution',
    yield: '30-40 tons per hectare',
    suitableRegions: ['Central', 'Eastern', 'Western', 'Nyanza'],
    climateZone: 'Tropical Wet',
    soilType: ['Loamy', 'Laterite', 'Alluvial'],
    plantingTime: 'March-May',
    harvestTime: '9-12 months after planting',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: '4',
    name: 'Tea',
    rainfallRequirement: 'high',
    description: 'Premium cash crop that requires high rainfall and well-drained acidic soils, Kenya\'s top export crop.',
    growingSeason: 'Perennial - regular harvesting',
    waterRequirement: 'High - 1800-2500mm annually',
    yield: '2-4 tons per hectare (processed tea)',
    suitableRegions: ['Central', 'Rift Valley', 'Western'],
    climateZone: 'Highland Tropical',
    soilType: ['Volcanic', 'Loamy', 'Acidic'],
    plantingTime: 'April-May',
    harvestTime: 'Throughout the year',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: '5',
    name: 'Coffee',
    rainfallRequirement: 'high',
    description: 'High-value cash crop requiring consistent rainfall and well-drained soils, grown in Kenyan highlands.',
    growingSeason: 'Perennial - seasonal harvesting',
    waterRequirement: 'High - 1000-1500mm annually',
    yield: '1-2 tons per hectare (processed coffee)',
    suitableRegions: ['Central', 'Rift Valley', 'Eastern'],
    climateZone: 'Highland Tropical',
    soilType: ['Volcanic', 'Red Loam', 'Well-drained'],
    plantingTime: 'April-May',
    harvestTime: 'October-December',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: '6',
    name: 'Maize (Highland)',
    rainfallRequirement: 'high',
    description: 'Staple food crop for high rainfall areas, main food security crop in Kenya.',
    growingSeason: '4-5 months',
    waterRequirement: 'High - 800-1200mm annually',
    yield: '3-6 tons per hectare',
    suitableRegions: ['Central', 'Western', 'Nyanza', 'Rift Valley'],
    climateZone: 'Highland Tropical',
    soilType: ['Loamy', 'Clay Loam', 'Volcanic'],
    plantingTime: 'March-April',
    harvestTime: 'July-August',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  
  // Low rainfall seeds suitable for Kenya
  {
    _id: '7',
    name: 'Sorghum',
    rainfallRequirement: 'low',
    description: 'Drought-tolerant grain crop suitable for dry farming, traditional crop in arid areas.',
    growingSeason: '3-4 months',
    waterRequirement: 'Low - 400-600mm annually',
    yield: '1-2.5 tons per hectare',
    suitableRegions: ['Eastern', 'North Eastern', 'Coast', 'Rift Valley'],
    climateZone: 'Semi-Arid',
    soilType: ['Sandy Loam', 'Clay', 'Alluvial'],
    plantingTime: 'March-April',
    harvestTime: 'July-August',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: '8',
    name: 'Millet (Pearl Millet)',
    rainfallRequirement: 'low',
    description: 'Drought-resistant cereal crop ideal for arid and semi-arid regions, traditional staple.',
    growingSeason: '2.5-3 months',
    waterRequirement: 'Low - 300-500mm annually',
    yield: '0.8-1.5 tons per hectare',
    suitableRegions: ['Eastern', 'North Eastern', 'Coast'],
    climateZone: 'Arid',
    soilType: ['Sandy', 'Loamy', 'Well-drained'],
    plantingTime: 'March-April',
    harvestTime: 'June-July',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: '9',
    name: 'Cowpeas',
    rainfallRequirement: 'low',
    description: 'Drought-tolerant legume that thrives in low rainfall conditions, important protein source.',
    growingSeason: '2.5-3 months',
    waterRequirement: 'Low - 300-400mm annually',
    yield: '0.6-1.2 tons per hectare',
    suitableRegions: ['Eastern', 'Coast', 'North Eastern', 'Rift Valley'],
    climateZone: 'Semi-Arid',
    soilType: ['Sandy Loam', 'Clay Loam'],
    plantingTime: 'March-April',
    harvestTime: 'June-July',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: '10',
    name: 'Green Grams (Mung Beans)',
    rainfallRequirement: 'low',
    description: 'Drought-resistant legume popular in arid areas, high-value export crop.',
    growingSeason: '2.5-3 months',
    waterRequirement: 'Low - 350-500mm annually',
    yield: '0.5-1 ton per hectare',
    suitableRegions: ['Eastern', 'Rift Valley', 'Coast'],
    climateZone: 'Semi-Arid',
    soilType: ['Sandy Loam', 'Red Soil'],
    plantingTime: 'March-April',
    harvestTime: 'June-July',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: '11',
    name: 'Pigeon Peas',
    rainfallRequirement: 'low',
    description: 'Drought-resistant legume that thrives in low rainfall conditions, traditional staple.',
    growingSeason: '4-5 months',
    waterRequirement: 'Low - 400-600mm annually',
    yield: '0.8-1.5 tons per hectare',
    suitableRegions: ['Eastern', 'Coast', 'Rift Valley'],
    climateZone: 'Semi-Arid',
    soilType: ['Sandy Loam', 'Clay'],
    plantingTime: 'March-April',
    harvestTime: 'July-August',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: '12',
    name: 'Cassava',
    rainfallRequirement: 'low',
    description: 'Drought-tolerant root crop that can grow with minimal rainfall, important food security crop.',
    growingSeason: '8-12 months',
    waterRequirement: 'Low - 500-800mm annually',
    yield: '15-25 tons per hectare',
    suitableRegions: ['Western', 'Nyanza', 'Coast', 'Eastern'],
    climateZone: 'Semi-Arid',
    soilType: ['Sandy Loam', 'Clay Loam', 'Laterite'],
    plantingTime: 'March-May',
    harvestTime: '8-12 months after planting',
    createdAt: new Date(),
    updatedAt: new Date()
  }
];

const mockLocations: Location[] = [
  // High rainfall locations in Kenya
  {
    _id: '1',
    name: 'Nairobi',
    region: 'Nairobi County',
    country: 'Kenya',
    rainfallPattern: 'high',
    annualRainfall: 1000,
    rainySeason: 'March-May (Long rains), October-December (Short rains)',
    climateZone: 'Highland Tropical',
    temperature: { min: 12, max: 28, average: 20 },
    soilType: ['Red Clay', 'Loamy'],
    coordinates: { latitude: -1.2921, longitude: 36.8219 },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: '2',
    name: 'Kisumu',
    region: 'Kisumu County',
    country: 'Kenya',
    rainfallPattern: 'high',
    annualRainfall: 1200,
    rainySeason: 'March-May (Long rains), October-December (Short rains)',
    climateZone: 'Tropical Wet',
    temperature: { min: 16, max: 32, average: 24 },
    soilType: ['Clay Loam', 'Alluvial'],
    coordinates: { latitude: -0.0917, longitude: 34.7680 },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: '3',
    name: 'Kakamega',
    region: 'Kakamega County',
    country: 'Kenya',
    rainfallPattern: 'high',
    annualRainfall: 1900,
    rainySeason: 'March-May (Long rains), August-October (Short rains)',
    climateZone: 'Tropical Wet',
    temperature: { min: 14, max: 30, average: 22 },
    soilType: ['Clay Loam', 'Laterite'],
    coordinates: { latitude: 0.2842, longitude: 34.7519 },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: '4',
    name: 'Embu',
    region: 'Embu County',
    country: 'Kenya',
    rainfallPattern: 'high',
    annualRainfall: 1400,
    rainySeason: 'March-May (Long rains), October-December (Short rains)',
    climateZone: 'Highland Tropical',
    temperature: { min: 12, max: 26, average: 19 },
    soilType: ['Volcanic', 'Red Loam'],
    coordinates: { latitude: -0.5313, longitude: 37.4512 },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: '5',
    name: 'Meru',
    region: 'Meru County',
    country: 'Kenya',
    rainfallPattern: 'high',
    annualRainfall: 1250,
    rainySeason: 'March-May (Long rains), October-December (Short rains)',
    climateZone: 'Highland Tropical',
    temperature: { min: 11, max: 25, average: 18 },
    soilType: ['Volcanic', 'Loamy'],
    coordinates: { latitude: 0.0470, longitude: 37.6495 },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: '6',
    name: 'Nakuru',
    region: 'Nakuru County',
    country: 'Kenya',
    rainfallPattern: 'high',
    annualRainfall: 900,
    rainySeason: 'March-May (Long rains), October-December (Short rains)',
    climateZone: 'Highland Semi-Arid',
    temperature: { min: 10, max: 28, average: 19 },
    soilType: ['Volcanic', 'Loamy'],
    coordinates: { latitude: -0.3031, longitude: 36.0695 },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: '7',
    name: 'Eldoret',
    region: 'Uasin Gishu County',
    country: 'Kenya',
    rainfallPattern: 'high',
    annualRainfall: 1100,
    rainySeason: 'March-May (Long rains), August-October (Short rains)',
    climateZone: 'Highland Tropical',
    temperature: { min: 10, max: 26, average: 18 },
    soilType: ['Volcanic', 'Red Loam'],
    coordinates: { latitude: 0.5143, longitude: 35.2698 },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: '8',
    name: 'Mombasa',
    region: 'Mombasa County',
    country: 'Kenya',
    rainfallPattern: 'high',
    annualRainfall: 1200,
    rainySeason: 'April-June (Long rains), October-December (Short rains)',
    climateZone: 'Tropical Coastal',
    temperature: { min: 22, max: 33, average: 27 },
    soilType: ['Sandy Loam', 'Coralline'],
    coordinates: { latitude: -4.0435, longitude: 39.6682 },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  
  // Low rainfall locations in Kenya
  {
    _id: '9',
    name: 'Garissa',
    region: 'Garissa County',
    country: 'Kenya',
    rainfallPattern: 'low',
    annualRainfall: 350,
    rainySeason: 'April-May (Limited rains)',
    climateZone: 'Arid',
    temperature: { min: 22, max: 38, average: 30 },
    soilType: ['Sandy', 'Alluvial'],
    coordinates: { latitude: -0.4528, longitude: 39.6460 },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: '10',
    name: 'Wajir',
    region: 'Wajir County',
    country: 'Kenya',
    rainfallPattern: 'low',
    annualRainfall: 280,
    rainySeason: 'April-May (Limited rains)',
    climateZone: 'Arid',
    temperature: { min: 21, max: 37, average: 29 },
    soilType: ['Sandy', 'Clay'],
    coordinates: { latitude: 1.7471, longitude: 40.0574 },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: '11',
    name: 'Mandera',
    region: 'Mandera County',
    country: 'Kenya',
    rainfallPattern: 'low',
    annualRainfall: 250,
    rainySeason: 'April-May (Limited rains)',
    climateZone: 'Arid',
    temperature: { min: 23, max: 39, average: 31 },
    soilType: ['Sandy', 'Alluvial'],
    coordinates: { latitude: 3.9377, longitude: 41.8569 },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: '12',
    name: 'Marsabit',
    region: 'Marsabit County',
    country: 'Kenya',
    rainfallPattern: 'low',
    annualRainfall: 400,
    rainySeason: 'March-May (Limited rains)',
    climateZone: 'Semi-Arid',
    temperature: { min: 16, max: 32, average: 24 },
    soilType: ['Sandy Loam', 'Volcanic'],
    coordinates: { latitude: 2.3286, longitude: 37.9892 },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: '13',
    name: 'Turkana',
    region: 'Turkana County',
    country: 'Kenya',
    rainfallPattern: 'low',
    annualRainfall: 300,
    rainySeason: 'April-May (Limited rains)',
    climateZone: 'Arid',
    temperature: { min: 20, max: 40, average: 30 },
    soilType: ['Sandy', 'Alluvial'],
    coordinates: { latitude: 3.1219, longitude: 35.5977 },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: '14',
    name: 'Kitui',
    region: 'Kitui County',
    country: 'Kenya',
    rainfallPattern: 'low',
    annualRainfall: 500,
    rainySeason: 'March-May (Long rains), November-December (Short rains)',
    climateZone: 'Semi-Arid',
    temperature: { min: 16, max: 32, average: 24 },
    soilType: ['Sandy Loam', 'Red Soil'],
    coordinates: { latitude: -1.3743, longitude: 38.0106 },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: '15',
    name: 'Machakos',
    region: 'Machakos County',
    country: 'Kenya',
    rainfallPattern: 'low',
    annualRainfall: 600,
    rainySeason: 'March-May (Long rains), October-December (Short rains)',
    climateZone: 'Semi-Arid',
    temperature: { min: 14, max: 30, average: 22 },
    soilType: ['Red Clay', 'Sandy Loam'],
    coordinates: { latitude: -1.5178, longitude: 37.2635 },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: '16',
    name: 'Kajiado',
    region: 'Kajiado County',
    country: 'Kenya',
    rainfallPattern: 'low',
    annualRainfall: 550,
    rainySeason: 'March-May (Long rains), October-December (Short rains)',
    climateZone: 'Semi-Arid',
    temperature: { min: 13, max: 30, average: 21 },
    soilType: ['Sandy Clay', 'Volcanic'],
    coordinates: { latitude: -1.8599, longitude: 36.7819 },
    createdAt: new Date(),
    updatedAt: new Date()
  }
];

export { mockSeeds, mockLocations };